name: Delete Old Workflow Runs

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'The min days to keep'
        required: true
        default: "0"
      minimum_runs:
        description: 'The min runs to keep for each workflow'
        required: true
        default: "0"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}